FROM golang:1.22.1-alpine
WORKDIR /basic-crud

RUN apk --update-cache add gcc musl-dev 

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -ldflags '-w -s' -a -o ./bin/app ./cmd

RUN chmod +x /chessplay_backend/bin/*